name: drip
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - beautifulsoup4
  - dash
 # - dask
  - descartes
  - distributed
  - fiona
  - flask-caching
  - gdal
  - geopandas
  - gevent
  - gunicorn
  - joblib
  - matplotlib
  - netcdf4
  - numpy
  - numba
  - pandas
  - pip
  - psutil
  - pyproj
  - rasterio
  - scipy
  - shapely
  - spyder
  - toolz
  - tqdm
  - xarray
 # - pip:
  #  - salem
   # - werkeug
    #- dash_bootstrap_components
