name: drip
channels:
    - conda-forge
    - defaults
dependencies:
    - beautifulsoup4
    - bottleneck
    - dash
    - dash-bootstrap-components
    - dask
    - flask-caching
    - gfortran
    - pandas
    - python=3.10
    - rasterio
    - rioxarray
    - netcdf4
    - numpy
    - geopandas
    - pip
    - pytest
    - scipy
    - tqdm
    - xarray
    - yaml
    - pip:
       - addfips
