name: venv
channels:
  - defaults
  - conda-forge  
dependencies:
  - beautifulsoup4
  - dash==0.39.0
  - descartes==1.1.0
  - fiona==1.8.6
  - geopandas==0.4.1
  - joblib==0.13.2
  - matplotlib
  - netcdf4==1.4.2
  - numpy==1.16.2
  - pandas==0.24.1
  - psutil==5.5.0
  - pyproj==1.9.6
  - scipy==1.2.0
  - tqdm==4.30.0
  - xarray==0.11.2
  - pip
  - pip:
    - gunicorn
    - shapely==1.6.4.post2
    - salem==0.2.3
    - flask_caching==1.4.0
