name: drip
channels:
    - conda-forge
    - defaults
dependencies:
    - dash
    - dash-bootstrap-components
    - dask
    - flask-caching
    - geopandas
    - ipython
    - netcdf4
    - numba
    - numpy
    - pandas
    - pathos
    - pytest
    - python=3.9
    - rasterio
    - rioxarray
    - salem
    - scipy
    - spyder-kernels
    - tqdm
    - xarray
    - werkzeug
    - yaml
    - pip
    - pip:
       - addfips