"""Dataset options."""
INDEX_OPTIONS = [
    # {"label": "RI", "value": "ri"},
    {"label": "PDSI", "value": "pdsi"},
    {"label": "PDSI-Self Calibrated", "value": "scpdsi"},
    {"label": "Palmer Z Index", "value": "pzi"},
    {"label": "EDDI-1", "value": "eddi1"},
    {"label": "EDDI-2", "value": "eddi2"},
    {"label": "EDDI-3", "value": "eddi3"},
    {"label": "EDDI-4", "value": "eddi4"},
    {"label": "EDDI-5", "value": "eddi5"},
    {"label": "EDDI-6", "value": "eddi6"},
    {"label": "EDDI-7", "value": "eddi7"},
    {"label": "EDDI-8", "value": "eddi8"},
    {"label": "EDDI-9", "value": "eddi9"},
    {"label": "EDDI-10", "value": "eddi10"},
    {"label": "EDDI-11", "value": "eddi11"},
    {"label": "EDDI-12", "value": "eddi12"},
    {"label": "SPI-1", "value": "spi1"},
    {"label": "SPI-2", "value": "spi2"},
    {"label": "SPI-3", "value": "spi3"},
    {"label": "SPI-4", "value": "spi4"},
    {"label": "SPI-5", "value": "spi5"},
    {"label": "SPI-6", "value": "spi6"},
    {"label": "SPI-7", "value": "spi7"},
    {"label": "SPI-8", "value": "spi8"},
    {"label": "SPI-9", "value": "spi9"},
    {"label": "SPI-10", "value": "spi10"},
    {"label": "SPI-11", "value": "spi11"},
    {"label": "SPI-12", "value": "spi12"},
    {"label": "SPEI-1", "value": "spei1"},
    {"label": "SPEI-2", "value": "spei2"},
    {"label": "SPEI-3", "value": "spei3"},
    {"label": "SPEI-4", "value": "spei4"},
    {"label": "SPEI-5", "value": "spei5"},
    {"label": "SPEI-6", "value": "spei6"},
    {"label": "SPEI-7", "value": "spei7"},
    {"label": "SPEI-8", "value": "spei8"},
    {"label": "SPEI-9", "value": "spei9"},
    {"label": "SPEI-10", "value": "spei10"},
    {"label": "SPEI-11", "value": "spei11"},
    {"label": "SPEI-12", "value": "spei12"},
    {"label": "TMIN", "value": "tmin"},
    {"label": "TMAX", "value": "tmax"},
    {"label": "TDMEAN", "value": "tdmean"},
    {"label": "PPT", "value": "ppt"},
    {"label": "VPDMAX", "value": "vpdmax"},
    {"label": "VPDMIN", "value": "vpdmin"},
]

INDEX_NAMES = {
    # "ri": "NOAA CPC-Derived Rainfall Index",
    "pdsi": "Palmer Drought Severity Index",
    "scpdsi": "Self-Calibrated Palmer Drought Severity Index",
    "pzi": "Palmer Z Index",
    "eddi1": "Evaporative Demand Index - 1 month",
    "eddi2": "Evaporative Demand Index - 2 month",
    "eddi3": "Evaporative Demand Index - 3 month",
    "eddi4": "Evaporative Demand Index - 4 month",
    "eddi5": "Evaporative Demand Index - 5 month",
    "eddi6": "Evaporative Demand Index - 6 month",
    "eddi7": "Evaporative Demand Index - 7 month",
    "eddi8": "Evaporative Demand Index - 8 month",
    "eddi9": "Evaporative Demand Index - 9 month",
    "eddi10": "Evaporative Demand Index - 10 month",
    "eddi11": "Evaporative Demand Index - 11 month",
    "eddi12": "Evaporative Demand Index - 12 month",
    "spi1": "Standardized Precipitation Index - 1 month",
    "spi2": "Standardized Precipitation Index - 2 month",
    "spi3": "Standardized Precipitation Index - 3 month",
    "spi4": "Standardized Precipitation Index - 4 month",
    "spi5": "Standardized Precipitation Index - 5 month",
    "spi6": "Standardized Precipitation Index - 6 month",
    "spi7": "Standardized Precipitation Index - 7 month",
    "spi8": "Standardized Precipitation Index - 8 month",
    "spi9": "Standardized Precipitation Index - 9 month",
    "spi10": "Standardized Precipitation Index - 10 month",
    "spi11": "Standardized Precipitation Index - 11 month",
    "spi12": "Standardized Precipitation Index - 12 month",
    "spei1": "Standardized Precipitation-Evaporation Index - 1 month",
    "spei2": "Standardized Precipitation-Evaporation Index - 2 month",
    "spei3": "Standardized Precipitation-Evaporation Index - 3 month",
    "spei4": "Standardized Precipitation-Evaporation Index - 4 month",
    "spei5": "Standardized Precipitation-Evaporation Index - 5 month",
    "spei6": "Standardized Precipitation-Evaporation Index - 6 month",
    "spei7": "Standardized Precipitation-Evaporation Index - 7 month",
    "spei8": "Standardized Precipitation-Evaporation Index - 8 month",
    "spei9": "Standardized Precipitation-Evaporation Index - 9 month",
    "spei10": "Standardized Precipitation-Evaporation Index - 10 month",
    "spei11": "Standardized Precipitation-Evaporation Index - 11 month",
    "spei12": "Standardized Precipitation-Evaporation Index - 12 month",
    "tmin": "Temperature - Minimum (C)",
    "tmax": "Temperature - Maximum (C)",
    # "tmean": "Temperature - Mean (C)",
    "tdmean": "Dew Point Temperature - Mean (C)",
    "ppt": "Precipitation (mm)",
    "vpdmax": "Vapor Pressure Deficit - Maxmimumm",
    "vpdmin": "Vapor Pressure Deficit - Minimum"
}
